[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# [fuzz]
# depth = 50
# runs = 2000

[invariant]
depth = 50
runs = 2000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
